version: '3.9'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data

      # - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
