POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "brianjohnson@example.com",
  "password": "secret"
}
###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "danielwilson@example.com",
  "password": "secret"
}
###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "emilybrown@example.com",
  "password": "secret"
}
###